"""Emit ports/ch32/machine_uart_pins.h from the datasheet's per-pin function lists.

    python ports/ch32/gen_uart_pins.py path/to/CH32H417DS0.txt
    python tools/codeformat.py

The second step is not optional: uncrustify realigns the table as a block, so
the comment column depends on the longest entry and cannot sensibly be emitted
pre-aligned. Skipping it fails the "Check code formatting" CI job.

Generated rather than typed. A wrong AF number produces a UART that configures
cleanly, reports TXE=1 and TC=1, and puts nothing on the wire -- see the
"Alternate function mux" section of docs/hw/ch32h417-notes.md -- so the table
is the part most worth not getting wrong by hand.

Takes the datasheet as plain text: pdftotext, or whatever produced the cached
copy the port was developed against.
"""

import os
import re
import sys
from collections import defaultdict

DS = sys.argv[1] if len(sys.argv) > 1 else os.environ.get("CH32_DATASHEET_TXT", "")
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "machine_uart_pins.h")

if not DS:
    raise SystemExit(__doc__)

PIN_START = re.compile(r"\b(P[A-F]\d{1,2})\s+I/O\b")
FUNC = re.compile(r"\b(USART\d)_(TX|RX|CTS|RTS)\s*\(\s*AF(\d+)\s*\)", re.I)
SIGS = ("TX", "RX", "CTS", "RTS")

lines = open(DS, encoding="utf-8", errors="replace").read().splitlines()
blocks, cur = [], None
for line in lines:
    m = PIN_START.search(line)
    if m:
        cur = [m.group(1), []]
        blocks.append(cur)
    elif cur is not None:
        cur[1].append(line)

rows = []
seen = set()
for pin, body in blocks:
    port = ord(pin[1]) - ord("A")
    num = int(pin[2:])
    for m in FUNC.finditer(" ".join(body)):
        uart = int(m.group(1)[5:])
        sig = m.group(2).upper()
        af = int(m.group(3))
        key = (uart, sig, pin)
        if key in seen:
            continue
        seen.add(key)
        rows.append((uart, SIGS.index(sig), port * 16 + num, af, pin))

rows.sort(key=lambda r: (r[0], r[1], r[2]))

with open(OUT, "w", encoding="utf-8") as fh:
    fh.write("""/* USART pin/alternate-function table for the CH32H417.
 *
 * GENERATED by scratchpad/gen_uart_pins.py from the datasheet's per-pin
 * function lists. Do not edit by hand; regenerate instead.
 *
 * This part uses an STM32F4-style AF multiplexer, not the CH32V307-style
 * remap scheme, so "remapping" a UART means picking a different pin and its
 * AF number rather than flipping a remap bit. Every pin the datasheet lists
 * for a given signal is therefore usable, which is what this table encodes.
 *
 * A wrong AF number fails silently: the USART runs, STATR shows TXE=1 and
 * TC=1, BRR is right, and nothing reaches the wire. So is a missing AFIO
 * clock, which makes the AF writes themselves disappear.
 */
#ifndef MICROPY_INCLUDED_CH32_MACHINE_UART_PINS_H
#define MICROPY_INCLUDED_CH32_MACHINE_UART_PINS_H

#include <stdint.h>

enum { UART_SIG_TX = 0, UART_SIG_RX = 1, UART_SIG_CTS = 2, UART_SIG_RTS = 3 };

typedef struct _uart_pin_af_t {
    uint8_t uart;  // 1-8
    uint8_t sig;   // UART_SIG_*
    uint8_t pin;   // machine.Pin id: port * 16 + number
    uint8_t af;    // alternate function number for GPIO_PinAFConfig()
} uart_pin_af_t;

static const uart_pin_af_t uart_pin_af_table[] = {
""")
    last = None
    for uart, sigi, pid, af, pin in rows:
        if last != (uart, sigi):
            fh.write("    // USART%d %s\n" % (uart, SIGS[sigi]))
            last = (uart, sigi)
        fh.write(
            "    { %d, UART_SIG_%-3s, %3d, %2d },  // %s\n" % (uart, SIGS[sigi], pid, af, pin)
        )
    fh.write("};\n\n#endif // MICROPY_INCLUDED_CH32_MACHINE_UART_PINS_H\n")

print("wrote %d entries for %d USARTs" % (len(rows), len({r[0] for r in rows})))
for u in sorted({r[0] for r in rows}):
    per = defaultdict(list)
    for uart, sigi, pid, af, pin in rows:
        if uart == u:
            per[SIGS[sigi]].append(pin)
    print("  USART%d  " % u + "  ".join("%s:%d" % (s, len(per[s])) for s in SIGS))
